font_family JetBrainsMonoNL Nerd Font Mono
font_size 18.0
tab_bar_style powerline

remember_window_size no

initial_window_width  80c
initial_window_height 24c
initial_window_x  center
initial_window_y  center

include rose-pine-moon-theme.conf

map f11 toggle_fullscreen

map ctrl+shift+, load_config_file

map ctrl+equal            change_font_size all +1.0
map ctrl+minus           change_font_size all -1.0
map ctrl+0       change_font_size all 0

# Fix double trigger in Neovim for old versions of Kitty:
map enter send_text all \x0d
map backspace send_text all \x7f
map tab send_text all \x09
